### ISSUE TITLE
Update library dependencies to use illuminate\support version 5.*

### ISSUE THREAD

**Issue by thomasclaysonpowa** [stevebauman/eloquent-table#2]
Hi Steve,

Can you update your amazing library to use illuminate\support version 5.* at all please?

I have to use this version for another library and I can't seem to install both at once.

Here's the full composer error: stevebauman/eloquenttable v1.0.2 requires illuminate/support 4.* -> no matching package found.

Thanks
Thomas

**Comment by stevebauman** [comment]
Hey thomas, sorry about the delay on this! Been working on other packages. I'll work on this today, compatibility shouldn't be too hard to do here. I'll update here once it's been done.

**Comment by thomasclaysonpowa** [comment]
Wow that was really quick! Thanks for your response. Looking forward to using this package again.

**Comment by stevebauman** [comment]
No problem, Laravel 5 compatibility has just been added, use `1.1.*` version in your composer.json. I'll be adding tests shortly!
