### ISSUE TITLE
The requested package stevebauman/eloquenttable could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by thomasclaysonpowa** [stevebauman/eloquent-table#3]
Hi Steve,

Thanks for the update to the package for Laravel 5.

Unfortunately composer can't find it now and I'm getting the error above. I've tried using @dev as well.

Is this just a temporary glitch? Or am I doing something wrong?

Here's the inclusion in the composer file:

`"stevebauman/eloquenttable": "1.1.*"`

Thanks
Thomas

**Comment by thomasclaysonpowa** [comment]
`"stevebauman/eloquenttable": "dev-master"` is working. :+1:

**Comment by stevebauman** [comment]
Woops! You're right, packagist wasn't auto-updating my tagged releases. It's all set now, let me know if you have issues with `1.1.*`

**Comment by thomasclaysonpowa** [comment]
Working now! Thank you.
